### ISSUE TITLE
Research sensors for the weather station

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#1]
This includes: 

- What do we want to track?
- What do we need to order?
- How would we use them?
- Do they require any additional effort to get working? How much?

**Comment by SamanthaCra** [comment]
https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/wiki/Sensors

**Comment by fuzzyers** [comment]
[Parts List.pdf](https://github.com/user-attachments/files/16537080/Parts.List.pdf)
Created and Set off a parts list to Vaugh
