### ISSUE TITLE
Sensor Setup D-Block Roof

### ISSUE THREAD

**Issue by fuzzyers** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#11]
Setup Sensors on DBlock Rooftop.

We will need to decide how we will be powering these devices from remote location.

[ReasearchPowerIssue](https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/issues/12)

**Comment by SamanthaCra** [comment]
Relies on completion of  Investigate the state of what is on OP's roof #3

**Comment by fuzzyers** [comment]
![IMG_20241024_141535.jpg](https://github.com/user-attachments/assets/3fccb8e5-216e-485f-8f8b-8955d2d97078)
Mounted
