### ISSUE TITLE
Remote Sensor Power Research

### ISSUE THREAD

**Issue by fuzzyers** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#12]
We will need to investigate our option when it comes to powering all of out equipment that will be setup on the roof.

**Comment by SamanthaCra** [comment]
Come up with a solution as to how we can house the weather station on the roof #27 related issue.

**Comment by fuzzyers** [comment]
This has been completed we have used POE to power it and it is now setup on the roof.
