### ISSUE TITLE
Build a database for all the data to go in to. 

### ISSUE THREAD

**Issue by TomMc608** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#14]
This database will be the ground base for the visualisation and weather predictions for the front end.

**Comment by SamanthaCra** [comment]
CO2 Project use Postgres, we will possibly do the same.

**Comment by SamanthaCra** [comment]
Documented in https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/wiki/Installing-Postgres-on-DB-Server
