### ISSUE TITLE
Build an API to access the database. 

### ISSUE THREAD

**Issue by TomMc608** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#15]
After the database is built, we must build an API to facilitate future use of the data.

**Comment by SamanthaCra** [comment]
Relies on completion of #14

**Comment by SamanthaCra** [comment]
Get data sending to database #20

**Comment by fuzzyers** [comment]
We have a basic API created. [Backend](https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/wiki/Backend)
