### ISSUE TITLE
Get data sending to database

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#20]
Ge tthe sensor data from IoT sending to the database successfully.

**Comment by SamanthaCra** [comment]
Similar to Transmit Data LORA #13

**Comment by SamanthaCra** [comment]
https://www.thethingsindustries.com/docs/api/

**Comment by SamanthaCra** [comment]
It is possible to get HTTP sending but if we are already developing an API then this is the best solution. We will need to build a web hook in order for the api to take data and post it to the database.

**Comment by fuzzyers** [comment]
[Backend Wiki](https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/wiki/Backend)

I have assembled a basic backend capable of ingesting data for temperature and humidity as a prototype.

Aswell as a very simplistic Webhook although it's only been setup to a local PostgreSQL database.
