### ISSUE TITLE
Build a webhook for TTN

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#21]
We need a webhook built in order to start the process of getting sensor data from The Things Network.

**Comment by fuzzyers** [comment]
I have created a very basic webhook that can be used for ingesting data locally it can be seen documented in [Backend](https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/wiki/Backend)
