### ISSUE TITLE
Come up with a solution as to how we can house the weather station on the roof

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#27]
Now that we have access, we need to put a plan together of requirements for our sensors and how they will come together on the roof.

**Comment by kierenblack** [comment]
The pole can be mounted using a pipe clamp

**Comment by kierenblack** [comment]
Rob is looking into some pipe and scaffold clamps to clamp the weather station to.

**Comment by fuzzyers** [comment]
i have found this [waterproofbox](https://www.mitre10.co.nz/shop/cordtech-weatherproof-power-box-345-x-210-x-125mm/p/270766?store=28&gad_source=1&gclid=EAIaIQobChMIpoL4gIKyiAMVkSiDAx0rBzeTEAQYAiABEgLtNvD_BwE&gclsrc=aw.ds) with cable access sold at mitre 10

**Comment by kierenblack** [comment]
I have left a length of pipe with 2 clamps in the hardware room to be used when the weather station is ready to go up to the roof.

**Comment by fuzzyers** [comment]
![image](https://github.com/user-attachments/assets/8ae0e56d-8b85-46cc-8512-a6c2d6a75624)
We have settled on one of these waterproof boxes from mitre 10 which we have spray painted white to help keep them cool
