### ISSUE TITLE
Create a Balena gmail account for the team. 

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#4]
https://www.balena.io/cloud

**Comment by SamanthaCra** [comment]
![image](https://github.com/user-attachments/assets/cc7af408-cd5d-4213-9837-c103c3ca6ec0)

**Comment by kierenblack** [comment]
email has been created: cloudywithachanceoflora@gmail.com.
balena cloud account has been created also
