### ISSUE TITLE
Deploy docker container in Balena Cloud

### ISSUE THREAD

**Issue by kierenblack** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#5]
Deploy a docker container in balena and assign to the fleet weather_station.

Useful links - 
[https://github.com/xoseperez/basicstation-docker](https://github.com/xoseperez/basicstation-docker)

**Comment by SamanthaCra** [comment]
This is redundant, gateway we have is already set up and connected to OP account.
