### ISSUE TITLE
Test existing CO2 Sensors

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#6]
There are a few existing Co2 sensors, they need tested and verified to see if they are giving accurate readings.

**Comment by SamanthaCra** [comment]
Please contribute to the wiki page if you work on this: https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/wiki/CO2-Requirements

**Comment by SamanthaCra** [comment]
@kierenblack got the log in for the polytech's IoT account. With this he created an application for us to add test devices to.

**Comment by fuzzyers** [comment]
By now we thoroughly tested and got a good understanding of how the feathers work and the c02 sensors we have established working code that can be used.
