### ISSUE TITLE
Set up new Co2 sensors

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#7]
There are a range of new Co2 sensors that need to be breadboarded and tested.

**Comment by SamanthaCra** [comment]
Martin requested as many as possible.

**Comment by SamanthaCra** [comment]
![image](https://github.com/user-attachments/assets/a1aba0d3-d67c-4c6e-868b-1021ecef67b0)
https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/tree/sc-co2-test

**Comment by kierenblack** [comment]
In the TinyLora.h library file, please ensure you add `#define AU915` on line 73 before
```
/** Region configuration*/
#if !defined(EU863) && !defined(AU915) && !defined(AS920)
#define US902 ///< Used in USA, Canada and South America
#endif
```

**Comment by fuzzyers** [comment]
![IMG_20240901_130735.jpg](https://github.com/user-attachments/assets/4bc638ed-7b98-49ea-a026-598e42eadc4d)

So we have 3 complete sensors as well as 2 breadboarded.
We are waiting on more female header pins to continue with this process.

**Comment by fuzzyers** [comment]
We have finished development on sensors for this sprint we await more parts in the future our next steps will include getting the developed ones in cases and then moving them on to the c02 team
