### ISSUE TITLE
Postgres: Schema

### ISSUE THREAD

**Issue by fuzzyers** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#77]
We will need to create a schema for our database going forward so anyone doing data related work will have the same template to follow.

**Comment by SamanthaCra** [comment]
Started now, will refine and review

**Comment by SamanthaCra** [comment]
Updated in https://github.com/OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa/wiki/Database-Server
