### ISSUE TITLE
Test temperature sensors

### ISSUE THREAD

**Issue by SamanthaCra** [OtagoPolytechnic/Cloudy-with-a-Chance-of-LoRa#9]
Adafruit 32u4 boards with basic temperature sensors. Testing them for a reading and connecting to The Things Network.

**Comment by kierenblack** [comment]
There is some startup code at 3bc8c4a1a3944b14ba820b6ea63a7c25c0000499

in the arduibo library ubder MCCI_LoRaWAN_LMIC_library/project_config/lmic_project_config.h comment out `#define CFG_us915 1` and uncomment `#define CFG_au915 1`

the library is at https://github.com/mcci-catena/arduino-lmic

**Comment by SamanthaCra** [comment]
Some of the temperature sensors are working
![image](https://github.com/user-attachments/assets/d983dbb1-366b-4cb3-b477-7cb2e86f796d)

**Comment by SamanthaCra** [comment]
We have working code that verifies if a sensor works or not.
